// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: proto/tide/asr/v1/asr.proto

package asrv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamingRecognizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamingRecognizeRequest) Reset() {
	*x = StreamingRecognizeRequest{}
	mi := &file_proto_tide_asr_v1_asr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamingRecognizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamingRecognizeRequest) ProtoMessage() {}

func (x *StreamingRecognizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tide_asr_v1_asr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamingRecognizeRequest.ProtoReflect.Descriptor instead.
func (*StreamingRecognizeRequest) Descriptor() ([]byte, []int) {
	return file_proto_tide_asr_v1_asr_proto_rawDescGZIP(), []int{0}
}

func (x *StreamingRecognizeRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// AudioProgress 表示本次识别流的累计音频处理进度。
// 与是否产生识别文本无关；静音音频也应推进处理进度。
type AudioProgress struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 从本次流起点开始，连续完成处理的原始音频字节数。
	// 不包含协议头或控制消息，按流单调不减。
	// 仅收到音频或将音频放入内部队列，不算完成处理。
	ProcessedAudioBytes uint64 `protobuf:"varint,1,opt,name=processed_audio_bytes,json=processedAudioBytes,proto3" json:"processed_audio_bytes,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AudioProgress) Reset() {
	*x = AudioProgress{}
	mi := &file_proto_tide_asr_v1_asr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioProgress) ProtoMessage() {}

func (x *AudioProgress) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tide_asr_v1_asr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioProgress.ProtoReflect.Descriptor instead.
func (*AudioProgress) Descriptor() ([]byte, []int) {
	return file_proto_tide_asr_v1_asr_proto_rawDescGZIP(), []int{1}
}

func (x *AudioProgress) GetProcessedAudioBytes() uint64 {
	if x != nil {
		return x.ProcessedAudioBytes
	}
	return 0
}

type StreamingRecognizeResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SegmentId string                 `protobuf:"bytes,1,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`
	Text      string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	IsFinal   bool                   `protobuf:"varint,3,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	// 存在时，本条响应只表示处理进度；segment_id、text 应为空，is_final 应为 false。
	// 不存在时，按原有识别结果解析。
	Progress      *AudioProgress `protobuf:"bytes,4,opt,name=progress,proto3" json:"progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamingRecognizeResponse) Reset() {
	*x = StreamingRecognizeResponse{}
	mi := &file_proto_tide_asr_v1_asr_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamingRecognizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamingRecognizeResponse) ProtoMessage() {}

func (x *StreamingRecognizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tide_asr_v1_asr_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamingRecognizeResponse.ProtoReflect.Descriptor instead.
func (*StreamingRecognizeResponse) Descriptor() ([]byte, []int) {
	return file_proto_tide_asr_v1_asr_proto_rawDescGZIP(), []int{2}
}

func (x *StreamingRecognizeResponse) GetSegmentId() string {
	if x != nil {
		return x.SegmentId
	}
	return ""
}

func (x *StreamingRecognizeResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *StreamingRecognizeResponse) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

func (x *StreamingRecognizeResponse) GetProgress() *AudioProgress {
	if x != nil {
		return x.Progress
	}
	return nil
}

var File_proto_tide_asr_v1_asr_proto protoreflect.FileDescriptor

const file_proto_tide_asr_v1_asr_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/tide/asr/v1/asr.proto\x12\vtide.asr.v1\"/\n" +
	"\x19StreamingRecognizeRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"C\n" +
	"\rAudioProgress\x122\n" +
	"\x15processed_audio_bytes\x18\x01 \x01(\x04R\x13processedAudioBytes\"\xa2\x01\n" +
	"\x1aStreamingRecognizeResponse\x12\x1d\n" +
	"\n" +
	"segment_id\x18\x01 \x01(\tR\tsegmentId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x19\n" +
	"\bis_final\x18\x03 \x01(\bR\aisFinal\x126\n" +
	"\bprogress\x18\x04 \x01(\v2\x1a.tide.asr.v1.AudioProgressR\bprogress2w\n" +
	"\n" +
	"ASRService\x12i\n" +
	"\x12StreamingRecognize\x12&.tide.asr.v1.StreamingRecognizeRequest\x1a'.tide.asr.v1.StreamingRecognizeResponse(\x010\x01B8Z6github.com/secacy/tide-artisan/proto/tide/asr/v1;asrv1b\x06proto3"

var (
	file_proto_tide_asr_v1_asr_proto_rawDescOnce sync.Once
	file_proto_tide_asr_v1_asr_proto_rawDescData []byte
)

func file_proto_tide_asr_v1_asr_proto_rawDescGZIP() []byte {
	file_proto_tide_asr_v1_asr_proto_rawDescOnce.Do(func() {
		file_proto_tide_asr_v1_asr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tide_asr_v1_asr_proto_rawDesc), len(file_proto_tide_asr_v1_asr_proto_rawDesc)))
	})
	return file_proto_tide_asr_v1_asr_proto_rawDescData
}

var file_proto_tide_asr_v1_asr_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_tide_asr_v1_asr_proto_goTypes = []any{
	(*StreamingRecognizeRequest)(nil),  // 0: tide.asr.v1.StreamingRecognizeRequest
	(*AudioProgress)(nil),              // 1: tide.asr.v1.AudioProgress
	(*StreamingRecognizeResponse)(nil), // 2: tide.asr.v1.StreamingRecognizeResponse
}
var file_proto_tide_asr_v1_asr_proto_depIdxs = []int32{
	1, // 0: tide.asr.v1.StreamingRecognizeResponse.progress:type_name -> tide.asr.v1.AudioProgress
	0, // 1: tide.asr.v1.ASRService.StreamingRecognize:input_type -> tide.asr.v1.StreamingRecognizeRequest
	2, // 2: tide.asr.v1.ASRService.StreamingRecognize:output_type -> tide.asr.v1.StreamingRecognizeResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_tide_asr_v1_asr_proto_init() }
func file_proto_tide_asr_v1_asr_proto_init() {
	if File_proto_tide_asr_v1_asr_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tide_asr_v1_asr_proto_rawDesc), len(file_proto_tide_asr_v1_asr_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tide_asr_v1_asr_proto_goTypes,
		DependencyIndexes: file_proto_tide_asr_v1_asr_proto_depIdxs,
		MessageInfos:      file_proto_tide_asr_v1_asr_proto_msgTypes,
	}.Build()
	File_proto_tide_asr_v1_asr_proto = out.File
	file_proto_tide_asr_v1_asr_proto_goTypes = nil
	file_proto_tide_asr_v1_asr_proto_depIdxs = nil
}
